### ISSUE TITLE
Python3 branch: MapEditor init crash loading E4M7

### ISSUE THREAD

**Issue by JPLeBreton** [devinacker/omgifol#11]
This code:

```
import omg
inwad = omg.WAD()
inwad.from_file('doom.wad')
ed = omg.MapEditor(inwad.maps['E4M7'])
```

gives the following error:

```
Traceback (most recent call last):
  File "e4m7_error.py", line 6, in <module>
    ed = omg.MapEditor(inwad.maps['E4M7'])
  File "omg/mapedit.py", line 161, in __init__
    self.from_lumps(from_lumps)
  File "omg/mapedit.py", line 183, in from_lumps
    self.sidedefs = self._unpack_lump(Sidedef,   m["SIDEDEFS"].data)
  File "omg/mapedit.py", line 176, in _unpack_lump
    return [class_(bytes=data[i:i+s]) for i in range(0,len(data),s)]
  File "omg/mapedit.py", line 176, in <listcomp>
    return [class_(bytes=data[i:i+s]) for i in range(0,len(data),s)]
  File "<struct>", line 12, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 4: ordinal not in range(128)
```

Running omgifol from Arch Linux, Python 3.5.1.

**Comment by devinacker** [comment]
fixed in 4f45fb4d1146658d9e9734d8fdbef4d3ac6c1ea9
